name: Cron Job Endpoint

on:
  schedule:
    # 6 AM, 2 PM, 10 PM Costa Rica (convertido a UTC)
    - cron: "0 12,20,4 * * *"

jobs:
  call-endpoint:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: |
          curl -X POST https://api-gonzalez-mobile-monorepo-production.up.railway.app/api/dynamic-prisma/main-structure \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
