name: Expo CI

on:
  push:
    paths:
      - "apps/mobile/**"
  pull_request:
    paths:
      - "apps/mobile/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/mobile
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm install
      - run: npm run lint
      - run: npm test

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Verify Expo project
        run: expo doctor
