name: Next.js CI

on:
  push:
    paths:
      - "apps/server/**"
  pull_request:
    paths:
      - "apps/server/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/server
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: npm run build
